version: "2"
services:
  dvwa:
    image: vax3/dvwa-selk
    networks:
      - secure
    ports:
      - 80:80
      - 3306:3306
    privileged: true

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    networks:
      - suricata

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - suricata
    ports:
      - 5601:5601

  logstash:
    image: docker.elastic.co/logstash/logstash:6.3.0
    entrypoint:
      - logstash
      - -f
      - /etc/logstash/conf.d/logstash.conf
    networks:
      - suricata
    volumes:
      - ~/project/docker/selk/Logstash-SELK/logstash.conf:/etc/logstash/conf.d/logstash.conf

  suricata:
    image: suricata
    environment:
      - FILEBEAT_TAG=logstash
      - HOME_NETWORK=172.16.3.0/24
      - LOGSTASH_HOST=logstash
      - LOGSTASH_PORT=5044
      - PATH_LOGS=/var/log/suricata/eve.json
    networks:
      - secure
      - suricata
    privileged: true

networks:
  secure:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.3.0/24
        gateway: 172.16.3.1
  suricata:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.2.0/24
        gateway: 172.16.2.1
